version: '3.7'

services:
  front-end:
    build: ./front-end
    ports:
      - "80:80"
    environment:
      BACK_END: "http://localhost:3001"
  back-end:
    build: ./back-end
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
    volumes:
      - db:/db
volumes:
  db: